"use client";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ShieldCheck, Save, Trash2, Power, Activity, WalletCards } from "lucide-react";
import { useParams } from "next/navigation";
import { useUmonApi } from "@/src/lib/api";
import FundingModal from "@/src/components/FundingModal";

export default function AgentDetailPage(){
  const {id}=useParams<{id:string}>(); const api=useUmonApi();
  const [stats,setStats]=useState<any>(null); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [amount,setAmount]=useState("500"); const [maxTxn,setMaxTxn]=useState("200"); const [daily,setDaily]=useState("400"); const [auto,setAuto]=useState(true); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{const d=await api.agentStats(id);setStats(d);setName(d.agent.name);setDescription(d.agent.description??"");setMaxTxn(String(d.agent.policy.max_transaction_paise/100));setDaily(String(d.agent.policy.daily_limit_paise/100));setAuto(Boolean(d.agent.policy.auto_purchase))},[api,id]);
  useEffect(()=>{load().catch(e=>alert(e instanceof Error?e.message:"Unable to load agent."))},[load]);
  async function save(){setSaving(true);try{await api.updateAgent(id,{name,description});await api.updatePolicy(id,{max_transaction:Number(maxTxn),daily_limit:Number(daily),auto_purchase:auto});await load()}catch(e){alert(e instanceof Error?e.message:"Unable to save agent.")}finally{setSaving(false)}}
  async function toggle(){try{await api.updateStatus(id,stats.agent.status==="ACTIVE"?"DISABLED":"ACTIVE");await load()}catch(e){alert(e instanceof Error?e.message:"Unable to change status.")}}
  async function revoke(){if(!confirm("Revoke this agent? Historical spending remains visible.")) return;try{await api.deleteAgent(id);await load()}catch(e){alert(e instanceof Error?e.message:"Unable to revoke agent.")}}
  if(!stats) return <main className="shell"><div className="loading">Loading agent…</div></main>;
  const limit=Number(stats.agent.policy.max_transaction_paise)/100; const dayLimit=Number(stats.agent.policy.daily_limit_paise)/100;
  return <main className="shell narrow"><a className="back-link" href="/agents"><ArrowLeft size={17}/>Back to agents</a><section className="detail-hero"><div><span className="eyebrow">PURCHASING AGENT</span><h1>{stats.agent.name}</h1><p>{stats.agent.description}</p></div><div className="detail-status"><ShieldCheck size={16}/>{stats.agent.status}</div></section>
    <section className="metrics-grid"><Metric label="Available balance" value={`₹${stats.agent.balance_available.toFixed(2)}`} icon={<WalletCards size={18}/>}/><Metric label="Spent today" value={`₹${(stats.spent_today_paise/100).toFixed(2)} / ₹${dayLimit.toFixed(2)}`} icon={<Activity size={18}/>}/><Metric label="This month" value={`₹${(stats.spent_this_month_paise/100).toFixed(2)}`} icon={<Activity size={18}/>}/><Metric label="Lifetime spent" value={`₹${(stats.lifetime_spent_paise/100).toFixed(2)}`} icon={<Activity size={18}/>}/></section>
    <section className="detail-grid"><article className="panel-card"><div className="panel-label">FUNDING</div><div className="big-number">₹{stats.agent.balance_available.toFixed(2)}</div><div className="subtle">Reserved ₹{(stats.agent.balance_reserved_paise/100).toFixed(2)}</div><div className="fund-row"><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="1"/><FundingModal agentId={id} amount={Number(amount)} onSuccess={load}/></div></article>
      <article className="panel-card"><div className="panel-label">AGENT PROFILE & GUARDRAILS</div><label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Description</span><input value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field"><span>Maximum per transaction</span><input value={maxTxn} onChange={e=>setMaxTxn(e.target.value)} type="number" min="1"/></label><label className="field"><span>Daily spending limit</span><input value={daily} onChange={e=>setDaily(e.target.value)} type="number" min="1"/></label><label className="switch-row"><span><strong>Autonomous purchasing</strong><small>When off, checkout returns CONFIRM instead of spending automatically.</small></span><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/></label><button className="secondary-button full" onClick={save} disabled={saving}><Save size={16}/>{saving?"Saving…":"Save agent"}</button></article></section>
    <section className="panel-card section-gap"><div className="section-heading"><div><span className="eyebrow">SPENDING HISTORY</span><h2>Ledger</h2></div></div><div className="history-list">{stats.ledger.map((x:any)=><div className="history-row" key={x.id}><span className={`ledger-dot ${x.type.toLowerCase()}`}/><div><strong>{x.type}</strong><small>{x.reason||x.reference}</small></div><b>{x.type==="CREDIT"?"+":"-"}₹{(x.amount_paise/100).toFixed(2)}</b></div>)}{!stats.ledger.length&&<div className="muted">No ledger activity yet.</div>}</div></section>
    <section className="panel-card section-gap"><div className="section-heading"><div><span className="eyebrow">AGENT ORDERS</span><h2>Orders</h2></div></div><div className="history-list">{stats.orders.map((x:any)=><div className="history-row" key={x.id}><div><strong>{x.id.slice(0,18)}</strong><small>{x.payment_method} · {x.status}</small></div><b>₹{(x.amount_paise/100).toFixed(2)}</b></div>)}{!stats.orders.length&&<div className="muted">No orders paid by this agent yet.</div>}</div></section>
    <section className="agent-danger"><button className="secondary-button" onClick={toggle}><Power size={15}/>{stats.agent.status==="ACTIVE"?"Disable agent":"Enable agent"}</button><button className="danger-button large" onClick={revoke}><Trash2 size={15}/>Revoke agent</button></section>
  </main>;
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <article className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong></article>}
