"use client";
import { useCallback, useEffect, useState } from "react";
import { ShoppingCart, Minus, Plus, Trash2, CreditCard, ArrowLeft } from "lucide-react";
import { useUmonApi } from "@/src/lib/api";
export default function CartPage(){
 const api=useUmonApi(); const [agents,setAgents]=useState<any[]>([]); const [agentId,setAgentId]=useState(""); const [cart,setCart]=useState<any>(null); const [busy,setBusy]=useState(false); const [decision,setDecision]=useState<any>(null);
 const loadAgents=useCallback(async()=>{const d=await api.agents(); const list=d.agents??[]; setAgents(list); setAgentId(cur=>cur||list[0]?.id||"")},[api]);
 const loadCart=useCallback(async()=>{if(agentId){const d=await api.cart(agentId);setCart(d.cart)}},[api,agentId]);
 useEffect(()=>{loadAgents().catch(console.error)},[loadAgents]); useEffect(()=>{loadCart().catch(console.error)},[loadCart]);
 async function change(id:string,q:number){setBusy(true);try{setCart((await api.updateCartItem(agentId,id,q)).cart)}catch(e){alert(e instanceof Error?e.message:"Unable to update cart")}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{setCart((await api.removeCartItem(agentId,id)).cart)}catch(e){alert(e instanceof Error?e.message:"Unable to remove item")}finally{setBusy(false)}}
 async function checkout(confirmed=false){setBusy(true);setDecision(null);try{setDecision(await api.checkoutWithAgentBalance(agentId,confirmed));}catch(e){setDecision({success:false,status:"ERROR",policy:{reason:e instanceof Error?e.message:"Checkout failed"}})}finally{setBusy(false)}}
 return <main className="shell narrow"><a className="back-link" href="/"><ArrowLeft size={17}/> Back to store</a><div className="section-heading standalone"><div><span className="eyebrow">CHECKOUT</span><h1>Your cart</h1></div></div>
 <div className="cart-toolbar"><div className="agent-select-wrap"><span>Shopping agent</span><select value={agentId} onChange={e=>{setAgentId(e.target.value);setDecision(null)}}>{agents.map(a=><option value={a.id} key={a.id}>{a.name} · ₹{a.balance_available.toFixed(2)}</option>)}</select></div><div className="cart-total">₹{((cart?.total_paise??0)/100).toFixed(2)}</div></div>
 {!cart?.items?.length?<section className="empty-card"><div className="empty-icon"><ShoppingCart size={24}/></div><h3>Your cart is empty</h3><p>Add a product from the store to start a purchase.</p><a className="secondary-button" href="/">Browse products</a></section>:<>
 <section className="cart-list">{cart.items.map((item:any)=><article className="cart-item" key={item.product_id}><img src={item.image} alt={item.name}/><div className="cart-item-main"><strong>{item.name}</strong><span>{item.category} · ₹{(item.unit_price_paise/100).toFixed(2)} each</span><div className="qty-controls"><button disabled={busy||item.quantity<=1} onClick={()=>change(item.product_id,item.quantity-1)}><Minus size={15}/></button><b>{item.quantity}</b><button disabled={busy} onClick={()=>change(item.product_id,item.quantity+1)}><Plus size={15}/></button><button className="danger-button" disabled={busy} onClick={()=>remove(item.product_id)}><Trash2 size={15}/></button></div></div><strong>₹{(item.line_total_paise/100).toFixed(2)}</strong></article>)}</section>
 <section className="checkout-card"><div className="summary-row"><span>Subtotal</span><strong>₹{((cart.subtotal_paise??0)/100).toFixed(2)}</strong></div><div className="summary-row"><span>Delivery</span><strong>₹{((cart.delivery_fee_paise??0)/100).toFixed(2)}</strong></div><div className="summary-row total"><span>Total</span><strong>₹{((cart.total_paise??0)/100).toFixed(2)}</strong></div><button className="primary-button checkout-button" disabled={busy} onClick={()=>checkout(false)}><CreditCard size={17}/> Pay with agent balance</button></section>
 {decision&&<section className={`decision-card ${decision.success?"success":decision.status==="CONFIRM"?"confirm":"blocked"}`}><span className="eyebrow">PURCHASE DECISION</span><h2>{decision.success?"Order confirmed":decision.status==="CONFIRM"?"Confirmation required":"Purchase blocked"}</h2><p>{decision.success?`Order ${decision.order.id} was created and marked paid using agent balance.`:decision.policy?.reason}</p>{decision.status==="CONFIRM"&&<button className="primary-button" disabled={busy} onClick={()=>checkout(true)}>Confirm and pay ₹{decision.total.toFixed(2)}</button>}{decision.success&&<a className="secondary-button" href="/orders">View orders</a>}</section>}
 </>}</main>
}
